export const GET_ALL_SESSIONS_REQUEST = "GET_ALL_SESSIONS_REQUEST";
export const GET_ALL_SESSIONS_SUCCESS = "GET_ALL_SESSIONS_SUCCESS";
export const GET_ALL_SESSIONS_FAILURE = "GET_ALL_SESSIONS_FAILURE";
